// Word loader utility
const FALLBACK_WORDS = [
  'ABSTRACT','ACCEPT','ACCOUNT','ADJUST','ADVICE','ANCIENT','ANOTHER','ARCHIVE','BALANCE','BATTERY',
  'BENEATH','BENEFIT','BETWEEN','BOTTLE','BRIDGE','CAPABLE','CAPTAIN','CAPTURE','CERTAIN','CHAPTER',
  'CHARITY','CHICKEN','CITIZEN','CLIMATE','COLLECT','COMBINE','COMFORT','COMMAND','COMMENT','COMPANY',
  'COMPETE','COMPLETE','CONCEPT','CONDUCT','CONFIRM','CONNECT','CONSIDER','CONTAIN','CONTENT','CONTEXT',
  'CONTROL','CONVERT','COUNTER','COUNTRY','CRYSTAL','CURRENT','DEFAULT','DEFENSE','DELIVER','DENSITY',
  'DEPOSIT','DESKTOP','DESTROY','DEVELOP','DIAMOND','DIGITAL','DISPLAY','DYNAMIC','ELEMENT','EMOTION',
  'ENHANCE','EVENING','EXAMINE','EXAMPLE','EXPENSE','EXPLAIN','EXPLORE','EXTREME','FASHION','FEATURE',
  'FESTIVAL','FICTION','FINANCE','FORTUNE','FORWARD','FREEDOM','FUNCTION','GALLERY','GENERAL','GENUINE',
  'GESTURE','GLACIER','GLIMPSE','GRAVITY','HARMONY','HARVEST','HEALTHY','HISTORY','HORIZON','HUMANITY',
  'IMAGINE','IMPROVE','INITIAL','INSPIRE','INSTANT','JOURNEY','JUSTICE','KINGDOM','LANGUAGE','LIBERTY',
  'MACHINE','MEASURE','MESSAGE','MILLION','MISSION','MYSTERY','NETWORK','NOTHING','OPERATE','OPINION',
  'ORGANIC','OUTLINE','PACKAGE','PARTNER','PASSION','PATTERN','PAYMENT','PERFECT','PERFORM','PICTURE',
  'PLASTIC','PLATFORM','PORTION','PREDICT','PREPARE','PRESENT','PREVENT','PRIMARY','PRIVATE','PROCESS',
  'PROFILE','PROGRAM','PROJECT','PROMISE','PROTECT','PROTEIN','PROVIDE','PURPOSE','QUALITY','QUARTER',
  'QUOTING','RADICAL','RAINBOW','REALITY','RECEIVE','REGULAR','RELEASE','REPLACE','REQUEST','REQUIRE',
  'RESERVE','RESPECT','RESPOND','RESTORE','REVERSE','ROUTINE','SCIENCE','SECTION','SEGMENT','SERVICE',
  'SESSION','SHELTER','SILENCE','SIMILAR','SOCIETY','SPEAKER','SPECIAL','STATION','STRANGE','STRETCH',
  'STUDENT','SUBJECT','SUCCESS','SUPPORT','SUPREME','SURFACE','SURPLUS','SURVIVE','TEACHER','TENSION',
  'THEATER','THERAPY','THOUGHT','THROUGH','TONIGHT','TRAFFIC','TRAINER','TRANSIT','TROUBLE','ULTIMATE',
  'UNIVERSE','UNKNOWN','UNUSUAL','UPGRADE','VALUABLE','VEHICLE','VERSION','VICTORY','VILLAGE','VIRTUAL',
  'VISIBLE','WAITING','WARNING','WEATHER','WELCOME','WESTERN','WHETHER','WHISPER','WITNESS','WORKING','WRITING'
];

let cachedWords: string[] | null = null;

export async function loadWords(): Promise<string[]> {
  if (cachedWords) {
    return cachedWords;
  }

  try {
    const response = await fetch('/words.txt');
    if (!response.ok) throw new Error('Failed to fetch words.txt');
    
    const text = await response.text();
    const wordList = text.split('\n')
      .map(w => w.trim().toUpperCase())
      .filter(w => 
        w.length >= 5 && 
        w.length <= 10 && 
        /^[A-Z]+$/.test(w)
      );
    
    cachedWords = [...new Set(wordList)];
    return cachedWords;
  } catch (error) {
    console.warn('Failed to load words.txt, using fallback words:', error);
    cachedWords = FALLBACK_WORDS;
    return cachedWords;
  }
}

